---
- name: Delete old docker
  apt:
    name: "{{ item }}"
    state: absent
  loop:
    - docker 
    - docker-engine
    - docker.io
    - containerd
    - runc

- name: Install software dependency
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
  loop:
    - apt-transport-https
    - ca-certificates
    - curl
    - gnupg-agent
    - software-properties-common

- name: Add apt key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Add docker repository
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu "{{ ansible_distribution_release }}" stable
    state: present

- name: Install docker
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
  loop:
    - "{{ DOCKER_VER }}"
  notify: restart docker

- name: Start docker
  systemd:
    state: started
    daemon_reload: yes
    name: docker
    enabled: yes

- name: Add current user in to docker group
  user:
    name: "{{ ansible_ssh_user }}"
    groups: docker
    append: yes