---
  apiVersion: extensions/v1beta1
  kind: Deployment
  metadata:
    name: nginx-deployment
    namespace: {{ k8s_namespace }}
  spec:
    selector:
      matchLabels:
        app: nginx
    replicas: {{ replica_count }}
    template:
      metadata:
        labels:
          app: nginx
      spec:
        containers:
        - name: nginx
          image: nginx:{{ tag }}
          ports:
          - containerPort: 80